apiVersion: v1
kind: Service
metadata:
  name: wordpress-lb
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 80 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      env: production
      app: wordpress
  template:  
    metadata:
      labels:
        app: wordpress
        env: production
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
        env:
        - name: "WORDPRESS_DB_HOST"
          value: mysql-lb
        - name: "WORDPRESS_DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: rpass
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-mount
          mountPath: /var/www/html
      volumes:
      - name: wordpress-mount
        persistentVolumeClaim:
          claimName: efs-wordpress